# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1b4ce59b43b4b933fd87f8fe0eefe76e115baec21d7194127bb6d0dca1865b177f3c4adb3c2edbbff82f254a72817b394b9422c26cc665224d186097a10a392

test:
  secret_key_base: aa0cf053999e96e4933a0b4e39acc8b7ed84d801b75fd1a704bd710b17293ad38bc4946a7680e6739ab20d352bfebc56ad0e6de8fc6f021e6b046e324757432b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
